# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f254b6567f22dbd6197e548e1c1ba660152f0c888dfa17f7e1c338b681abbb303af6ed0f00b7efbf6e036e3d0bba4a5793cd502f38bfb7415d29fbc1029e01b

test:
  secret_key_base: 526d1f10c65e5cb7e4b78dcd3fe905db53da61c7fcefab2f8152136a2714ded4ec7ebfc120bfed989329e02ccf217e96ccb4b6601d9c4fbd72c24a388fe93876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
